#include<iostream.h>
#include<conio.h>
class v
{int a,b,c,d,e;
 public:
   v()
   { //a=x;
    cout<<"\nhiiii";
   }
   void input();
   void output();
};
//   void v::input()
  // { cout<<"\nenter tow number:\n";
    // cin>>b;
//   }
   void v::output()
   {cout<<a<<"  "<<b<<"  "<<c<<"  "<<d<<"  "<<e;
   }
void main()
{clrscr();
 v o;
// o.input();
 o.output();
// v ob;


 getch();
}
